### ISSUE TITLE
 Inaccurate number of parameters from torchsummary

### ISSUE THREAD

**Issue by Thity** [Woodman718/CapsNets#3]
The number of parameters reported for CapsNet seems to be coming from [torchsummary](https://github.com/sksq96/pytorch-summary).

However, torchsummary parameter count is inaccurate for custom modules, in particular when parameters name is not "weight" or "bias" (see https://github.com/sksq96/pytorch-summary/issues/65). The count does not consider network.digits.W parameters that represent ~25% of CapsNet parameters.

**Comment by Woodman718** [comment]
The reported parameter count for CapsNet is obtained from torchsummary. However, it's worth noting that torchsummary's parameter count can be inaccurate when dealing with custom modules. In this case, it doesn't account for parameters in 'network.digits.W,' which amount to approximately 0.51 million, representing roughly 26% of CapsNet's total parameters. 
Thank you for your attention.
