### ISSUE TITLE
About the data augment

### ISSUE THREAD

**Issue by Franklin-sxs** [Woodman718/CapsNets#6]
Can you publish the code you use to perform data augmentation to handle imbalanced and split datasets?

**Comment by Woodman718** [comment]
Recently, I have been busy with other tasks and have not made further progress on the skin cancer project.
The part regarding image processing was posted on 'https://github.com/Woodman718/FixCaps/tree/main/augmentation' quite early.
I have uploaded the image processing code I will be using to the "tools" directory.

In fact, if you replace 'nn.AdaptiveMaxPool2d(20)' in 'model.py' with 'nn.FractionalMaxPool2d(2, output_size=(20))', it can improve the score by 1-2% even without using data augmentation. 
However, this may decrease the stability of the model.
